### ISSUE TITLE
 Exception ticking world

### ISSUE THREAD

**Issue by Akairilia** [CammiePone/Cammies-Combat-Tweaks#20]
Description: Exception ticking world

java.lang.IllegalArgumentException: Can't find attribute minecraft:generic.attack_damage
	at net.minecraft.entity.attribute.DefaultAttributeContainer.require(DefaultAttributeContainer:22)
	at net.minecraft.entity.attribute.DefaultAttributeContainer.getBaseValue(DefaultAttributeContainer:32)
	at net.minecraft.entity.attribute.AttributeContainer.getBaseValue(AttributeContainer:67)
	at net.minecraft.entity.LivingEntity.getAttributeBaseValue(LivingEntity:1867)
	at net.minecraft.server.world.ServerWorld.changeEntityStats(ServerWorld:15659)
	at net.minecraft.server.world.ServerWorld.handler$iop000$onMobSpawned(ServerWorld:15647)
	at net.minecraft.server.world.ServerWorld.spawnEntity(ServerWorld)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at net.minecraft.world.ServerWorldAccess.spawnEntityAndPassengers(ServerWorldAccess:11)
	at net.minecraft.world.SpawnHelper.spawnEntitiesInChunk(SpawnHelper:296)
	at net.minecraft.world.SpawnHelper.spawnEntitiesInChunk(SpawnHelper:209)
	at net.minecraft.world.SpawnHelper.spawn(SpawnHelper:197)
	at net.minecraft.server.world.ServerChunkManager.tickChunks(ServerChunkManager:377)
	at net.minecraft.server.world.ServerChunkManager.tick(ServerChunkManager:325)
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld:308)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:879)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:823)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer:99)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:270)
	at java.lang.Thread.run(Thread.java:833)

https://crashy.net/HjAIbRgiNDdQdw3Ratiq

**Comment by CammiePone** [comment]
1) the log is pretty useless since idk what version you're on or what mods you have
2) it's some other mod because minecraft:generic.attack_damage is the name of the attribute, meaning either you're trying to run this on an unsupported version, or you have a mod installed that changed the name of the attribute

**Comment by Akairilia** [comment]
> 1. the log is pretty useless since idk what version you're on or what mods you have
> 2. it's some other mod because minecraft:generic.attack_damage is the name of the attribute, meaning either you're trying to run this on an unsupported version, or you have a mod installed that changed the name of the attribute

All the info is on crashy, the link is right below the log

**Comment by CammiePone** [comment]
I prefer the full log. Crashy on mobile (when I first checked) was completely unusable as it only showed the same information you posted. I'm gonna guess to swap between relevant information, you had to go into some other menu.

**Comment by CammiePone** [comment]
Alright, so looks like you're on the right version for everything, but yeah that isn't a CCT issue. Something else changed the ID of the attribute. Find out whatever mod creates the `onMobSpawned()` method using Mixin Trace and report it to them. They're mixing into the ServerWorld class, so it'll probably be named ServerWorldMixin, but don't rely on that.

Also, don't use Crashy. It leaves out the top half of the crashlog anyways, which usually contains vital information.
